server:
  port: 8081

spring:
  application:
    name: TestRSS
  datasource:
    url: jdbc:mysql://db:3306/news?autoReconnect=true
    password: ${DATASOURCE_PWD}
    username: root
  jpa:
#    properties:
#      hibernate:
#        format_sql: true
    hibernate:
      ddl-auto: update
#    show-sql: true

app:
  openai:
    url: https://api.openai.com/v1/chat/completions
    API_KEY: ${API_KEY}
